### ISSUE TITLE
sh agent/scripts/replay.sh error

### ISSUE THREAD

**Issue by hlzhang109** [lil-lab/cerealbar#11]
File "hlzhang109/cerealbar/agent/data/partial_observation.py", line 14, in <module>
    VISIBILITY_MAP: Dict[Tuple[position.Position, rotation.Rotation], List[position.Position]] = pickle.load(infile)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by alsuhr-c** [comment]
Apologies for the delay. You are loading this file, correct? https://github.com/lil-lab/cerealbar/blob/master/agent/preprocessed/position_visibility.pkl

It's stored via Git LFS, so you likely need to directly pull the file. It could be the case that the file on your machine is only a pointer to the file on Git LFS, without the actual data.

By the way, there is a new version of the CerealBar game available here: https://github.com/lil-lab/cb2
