### ISSUE TITLE
Building the game

### ISSUE THREAD

**Issue by Yang011013** [lil-lab/cerealbar#12]
Hello! When I follow cerealbar\game\README.md to build the game for the WebGL version，it made this error“Assets/Unity Asset store/OutlineEffect/Outline.cs(49,17): error CS0103: The name `SetGame' does not exist in the current context”.  How can I fix it?

**Comment by yoavartzi** [comment]
I recommend using CB2 (cb2.ai) as much as possible. We don't have the ability to maintain this version much. But CC-ing @alsuhr-c in case she has a quick answer.
